function FastClick(a,f){function d(b,a){return function(){return b.apply(a,arguments)}}var g;f=f||{};this.trackingClick=!1;this.trackingClickStart=0;this.targetElement=null;this.lastTouchIdentifier=this.touchStartY=this.touchStartX=0;this.touchBoundary=f.touchBoundary||10;this.layer=a;this.tapDelay=f.tapDelay||200;if(!FastClick.notNeeded(a)){for(var b="onMouse onClick onTouchStart onTouchMove onTouchEnd onTouchCancel".split(" "),c=0,e=b.length;c<e;c++)this[b[c]]=d(this[b[c]],this);deviceIsAndroid&&
(a.addEventListener("mouseover",this.onMouse,!0),a.addEventListener("mousedown",this.onMouse,!0),a.addEventListener("mouseup",this.onMouse,!0));a.addEventListener("click",this.onClick,!0);a.addEventListener("touchstart",this.onTouchStart,!1);a.addEventListener("touchmove",this.onTouchMove,!1);a.addEventListener("touchend",this.onTouchEnd,!1);a.addEventListener("touchcancel",this.onTouchCancel,!1);Event.prototype.stopImmediatePropagation||(a.removeEventListener=function(b,c,e){var d=Node.prototype.removeEventListener;
"click"===b?d.call(a,b,c.hijacked||c,e):d.call(a,b,c,e)},a.addEventListener=function(b,c,e){var d=Node.prototype.addEventListener;"click"===b?d.call(a,b,c.hijacked||(c.hijacked=function(b){b.propagationStopped||c(b)}),e):d.call(a,b,c,e)});"function"===typeof a.onclick&&(g=a.onclick,a.addEventListener("click",function(b){g(b)},!1),a.onclick=null)}}
var deviceIsAndroid=0<navigator.userAgent.indexOf("Android"),deviceIsIOS=/iP(ad|hone|od)/.test(navigator.userAgent),deviceIsIOS4=deviceIsIOS&&/OS 4_\d(_\d)?/.test(navigator.userAgent),deviceIsIOSWithBadTarget=deviceIsIOS&&/OS ([6-9]|\d{2})_\d/.test(navigator.userAgent);FastClick.prototype.needsClick=function(a){switch(a.nodeName.toLowerCase()){case "button":case "select":case "textarea":if(a.disabled)return!0;break;case "input":if(deviceIsIOS&&"file"===a.type||a.disabled)return!0;break;case "label":case "video":return!0}return/\bneedsclick\b/.test(a.className)};
FastClick.prototype.needsFocus=function(a){switch(a.nodeName.toLowerCase()){case "textarea":return!0;case "select":return!deviceIsAndroid;case "input":switch(a.type){case "button":case "checkbox":case "file":case "image":case "radio":case "submit":return!1}return!a.disabled&&!a.readOnly;default:return/\bneedsfocus\b/.test(a.className)}};
FastClick.prototype.sendClick=function(a,f){var d,g;document.activeElement&&document.activeElement!==a&&document.activeElement.blur();g=f.changedTouches[0];d=document.createEvent("MouseEvents");d.initMouseEvent(this.determineEventType(a),!0,!0,window,1,g.screenX,g.screenY,g.clientX,g.clientY,!1,!1,!1,!1,0,null);d.forwardedTouchEvent=!0;a.dispatchEvent(d)};FastClick.prototype.determineEventType=function(a){return deviceIsAndroid&&"select"===a.tagName.toLowerCase()?"mousedown":"click"};
FastClick.prototype.focus=function(a){var f;deviceIsIOS&&a.setSelectionRange&&0!==a.type.indexOf("date")&&"time"!==a.type?(f=a.value.length,a.setSelectionRange(f,f)):a.focus()};FastClick.prototype.updateScrollParent=function(a){var f,d;f=a.fastClickScrollParent;if(!f||!f.contains(a)){d=a;do{if(d.scrollHeight>d.offsetHeight){f=d;a.fastClickScrollParent=d;break}d=d.parentElement}while(d)}f&&(f.fastClickLastScrollTop=f.scrollTop)};
FastClick.prototype.getTargetElementFromEventTarget=function(a){return a.nodeType===Node.TEXT_NODE?a.parentNode:a};
FastClick.prototype.onTouchStart=function(a){var f,d,g;if(1<a.targetTouches.length)return!0;f=this.getTargetElementFromEventTarget(a.target);d=a.targetTouches[0];if(deviceIsIOS){g=window.getSelection();if(g.rangeCount&&!g.isCollapsed)return!0;if(!deviceIsIOS4){if(d.identifier===this.lastTouchIdentifier)return a.preventDefault(),!1;this.lastTouchIdentifier=d.identifier;this.updateScrollParent(f)}}this.trackingClick=!0;this.trackingClickStart=a.timeStamp;this.targetElement=f;this.touchStartX=d.pageX;
this.touchStartY=d.pageY;a.timeStamp-this.lastClickTime<this.tapDelay&&a.preventDefault();return!0};FastClick.prototype.touchHasMoved=function(a){a=a.changedTouches[0];var f=this.touchBoundary;return Math.abs(a.pageX-this.touchStartX)>f||Math.abs(a.pageY-this.touchStartY)>f?!0:!1};FastClick.prototype.onTouchMove=function(a){if(!this.trackingClick)return!0;if(this.targetElement!==this.getTargetElementFromEventTarget(a.target)||this.touchHasMoved(a))this.trackingClick=!1,this.targetElement=null;return!0};
FastClick.prototype.findControl=function(a){return void 0!==a.control?a.control:a.htmlFor?document.getElementById(a.htmlFor):a.querySelector("button, input:not([type=hidden]), keygen, meter, output, progress, select, textarea")};
FastClick.prototype.onTouchEnd=function(a){var f,d,g=this.targetElement;if(!this.trackingClick)return!0;if(a.timeStamp-this.lastClickTime<this.tapDelay)return this.cancelNextClick=!0;this.cancelNextClick=!1;this.lastClickTime=a.timeStamp;f=this.trackingClickStart;this.trackingClick=!1;this.trackingClickStart=0;deviceIsIOSWithBadTarget&&(d=a.changedTouches[0],g=document.elementFromPoint(d.pageX-window.pageXOffset,d.pageY-window.pageYOffset)||g,g.fastClickScrollParent=this.targetElement.fastClickScrollParent);
d=g.tagName.toLowerCase();if("label"===d){if(f=this.findControl(g)){this.focus(g);if(deviceIsAndroid)return!1;g=f}}else if(this.needsFocus(g)){if(100<a.timeStamp-f||deviceIsIOS&&window.top!==window&&"input"===d)return this.targetElement=null,!1;this.focus(g);this.sendClick(g,a);deviceIsIOS&&"select"===d||(this.targetElement=null,a.preventDefault());return!1}if(deviceIsIOS&&!deviceIsIOS4&&(f=g.fastClickScrollParent)&&f.fastClickLastScrollTop!==f.scrollTop)return!0;this.needsClick(g)||(a.preventDefault(),
this.sendClick(g,a));return!1};FastClick.prototype.onTouchCancel=function(){this.trackingClick=!1;this.targetElement=null};FastClick.prototype.onMouse=function(a){return this.targetElement&&!a.forwardedTouchEvent&&a.cancelable?!this.needsClick(this.targetElement)||this.cancelNextClick?(a.stopImmediatePropagation?a.stopImmediatePropagation():a.propagationStopped=!0,a.stopPropagation(),a.preventDefault(),!1):!0:!0};
FastClick.prototype.onClick=function(a){if(this.trackingClick)return this.targetElement=null,this.trackingClick=!1,!0;if("submit"===a.target.type&&0===a.detail)return!0;a=this.onMouse(a);a||(this.targetElement=null);return a};
FastClick.prototype.destroy=function(){var a=this.layer;deviceIsAndroid&&(a.removeEventListener("mouseover",this.onMouse,!0),a.removeEventListener("mousedown",this.onMouse,!0),a.removeEventListener("mouseup",this.onMouse,!0));a.removeEventListener("click",this.onClick,!0);a.removeEventListener("touchstart",this.onTouchStart,!1);a.removeEventListener("touchmove",this.onTouchMove,!1);a.removeEventListener("touchend",this.onTouchEnd,!1);a.removeEventListener("touchcancel",this.onTouchCancel,!1)};
FastClick.notNeeded=function(a){var f,d;if("undefined"===typeof window.ontouchstart)return!0;if(d=+(/Chrome\/([0-9]+)/.exec(navigator.userAgent)||[,0])[1])if(deviceIsAndroid){if((f=document.querySelector("meta[name=viewport]"))&&(-1!==f.content.indexOf("user-scalable=no")||31<d&&document.documentElement.scrollWidth<=window.outerWidth))return!0}else return!0;return"none"===a.style.msTouchAction?!0:!1};FastClick.attach=function(a,f){return new FastClick(a,f)};
"undefined"!==typeof define&&define.amd?define(function(){return FastClick}):"undefined"!==typeof module&&module.exports?(module.exports=FastClick.attach,module.exports.FastClick=FastClick):window.FastClick=FastClick;(function(a){"function"===typeof define&&define.amd&&define.amd.jQuery?define(["jquery"],a):a(jQuery)})(function(a){function f(b){return b}function d(a){return decodeURIComponent(a.replace(b," "))}function g(b){0===b.indexOf('"')&&(b=b.slice(1,-1).replace(/\\"/g,'"').replace(/\\\\/g,"\\"));return c.json?JSON.parse(b):b}var b=/\+/g,c=a.cookie=function(b,h,l){if(void 0!==h){l=a.extend({},c.defaults,l);null===h&&(l.expires=-1);if("number"===typeof l.expires){var n=l.expires,r=l.expires=new Date;r.setDate(r.getDate()+
n)}h=c.json?JSON.stringify(h):String(h);return document.cookie=[encodeURIComponent(b),"=",c.raw?h:encodeURIComponent(h),l.expires?"; expires="+l.expires.toUTCString():"",l.path?"; path="+l.path:"",l.domain?"; domain="+l.domain:"",l.secure?"; secure":""].join("")}h=c.raw?f:d;l=document.cookie.split("; ");for(var n=b?null:{},r=0,k=l.length;r<k;r++){var m=l[r].split("="),p=h(m.shift()),m=h(m.join("="));if(b&&b===p){n=g(m);break}b||(n[p]=g(m))}return n};c.defaults={};a.removeCookie=function(b,c){return null!==
a.cookie(b)?(a.cookie(b,null,c),!0):!1}});(function(a){function f(){this.debug=!0;this._curInst=null;this._disabledInputs=[];this._inDialog=this._timepickerShowing=!1;this._dialogClass="ui-timepicker-dialog";this._mainDivId="ui-timepicker-div";this._inlineClass="ui-timepicker-inline";this._currentClass="ui-timepicker-current";this._dayOverClass="ui-timepicker-days-cell-over";this.regional=[];this.regional[""]={hourText:"Hour",minuteText:"Minute",amPmText:["AM","PM"],closeButtonText:"Done",nowButtonText:"Now",deselectButtonText:"Deselect"};
this._defaults={showOn:"focus",button:null,showAnim:"fadeIn",showOptions:{},appendText:"",beforeShow:null,onSelect:null,onClose:null,timeSeparator:":",periodSeparator:" ",showPeriod:!1,showPeriodLabels:!0,showLeadingZero:!0,showMinutesLeadingZero:!0,altField:"",defaultTime:"now",myPosition:"left top",atPosition:"left bottom",onHourShow:null,onMinuteShow:null,hours:{starts:0,ends:23},minutes:{starts:0,ends:55,interval:5,manual:[]},rows:4,showHours:!0,showMinutes:!0,optionalMinutes:!1,showCloseButton:!1,
showNowButton:!1,showDeselectButton:!1,maxTime:{hour:null,minute:null},minTime:{hour:null,minute:null}};a.extend(this._defaults,this.regional[""]);this.tpDiv=a('<div id="'+this._mainDivId+'" class="ui-timepicker ui-widget ui-helper-clearfix ui-corner-all " style="display: none"></div>')}function d(b,c){a.extend(b,c);for(var e in c)if(null==c[e]||void 0==c[e])b[e]=c[e];return b}a.extend(a.ui,{timepicker:{version:"0.3.3"}});var g=(new Date).getTime();a.extend(f.prototype,{markerClassName:"hasTimepicker",
log:function(){this.debug&&console.log.apply("",arguments)},_widgetTimepicker:function(){return this.tpDiv},setDefaults:function(b){d(this._defaults,b||{});return this},_attachTimepicker:function(b,c){var e=null,h;for(h in this._defaults){var l=b.getAttribute("time:"+h);if(l){e=e||{};try{e[h]=eval(l)}catch(d){e[h]=l}}}h=b.nodeName.toLowerCase();l="div"==h||"span"==h;b.id||(this.uuid+=1,b.id="tp"+this.uuid);var g=this._newInst(a(b),l);g.settings=a.extend({},c||{},e||{});"input"==h?(this._connectTimepicker(b,
g),this._setTimeFromField(g)):l&&this._inlineTimepicker(b,g)},_newInst:function(b,c){return{id:b[0].id.replace(/([^A-Za-z0-9_-])/g,"\\\\$1"),input:b,inline:c,tpDiv:c?a('<div class="'+this._inlineClass+' ui-timepicker ui-widget  ui-helper-clearfix"></div>'):this.tpDiv}},_connectTimepicker:function(b,c){var e=a(b);c.append=a([]);c.trigger=a([]);e.hasClass(this.markerClassName)||(this._attachments(e,c),e.addClass(this.markerClassName).keydown(this._doKeyDown).keyup(this._doKeyUp).bind("setData.timepicker",
function(b,a,e){c.settings[a]=e}).bind("getData.timepicker",function(b,a){return this._get(c,a)}),a.data(b,"timepicker",c))},_doKeyDown:function(b){var c=a.timepicker._getInst(b.target),e=!0;c._keyEvent=!0;if(a.timepicker._timepickerShowing)switch(b.keyCode){case 9:a.timepicker._hideTimepicker();e=!1;break;case 13:return a.timepicker._updateSelectedValue(c),a.timepicker._hideTimepicker(),!1;case 27:a.timepicker._hideTimepicker();break;default:e=!1}else 36==b.keyCode&&b.ctrlKey?a.timepicker._showTimepicker(this):
e=!1;e&&(b.preventDefault(),b.stopPropagation())},_doKeyUp:function(b){b=a.timepicker._getInst(b.target);a.timepicker._setTimeFromField(b);a.timepicker._updateTimepicker(b)},_attachments:function(b,c){var e=this._get(c,"appendText"),h=this._get(c,"isRTL");c.append&&c.append.remove();e&&(c.append=a('<span class="'+this._appendClass+'">'+e+"</span>"),b[h?"before":"after"](c.append));b.unbind("focus.timepicker",this._showTimepicker);b.unbind("click.timepicker",this._adjustZIndex);c.trigger&&c.trigger.remove();
e=this._get(c,"showOn");if("focus"==e||"both"==e)b.bind("focus.timepicker",this._showTimepicker),b.bind("click.timepicker",this._adjustZIndex);if("button"==e||"both"==e)e=this._get(c,"button"),null==e&&(e=a('<button class="ui-timepicker-trigger" type="button">...</button>'),b.after(e)),a(e).bind("click.timepicker",function(){a.timepicker._timepickerShowing&&a.timepicker._lastInput==b[0]?a.timepicker._hideTimepicker():c.input.is(":disabled")||a.timepicker._showTimepicker(b[0]);return!1})},_inlineTimepicker:function(b,
c){var e=a(b);e.hasClass(this.markerClassName)||(e.addClass(this.markerClassName).append(c.tpDiv).bind("setData.timepicker",function(b,a,e){c.settings[a]=e}).bind("getData.timepicker",function(b,a){return this._get(c,a)}),a.data(b,"timepicker",c),this._setTimeFromField(c),this._updateTimepicker(c),c.tpDiv.show())},_adjustZIndex:function(b){b=b.target||b;a.timepicker._getInst(b).tpDiv.css("zIndex",a.timepicker._getZIndex(b)+1)},_showTimepicker:function(b){b=b.target||b;"input"!=b.nodeName.toLowerCase()&&
(b=a("input",b.parentNode)[0]);if(!a.timepicker._isDisabledTimepicker(b)&&a.timepicker._lastInput!=b){a.timepicker._hideTimepicker();var c=a.timepicker._getInst(b);a.timepicker._curInst&&a.timepicker._curInst!=c&&a.timepicker._curInst.tpDiv.stop(!0,!0);var e=a.timepicker._get(c,"beforeShow");d(c.settings,e?e.apply(b,[b,c]):{});c.lastVal=null;a.timepicker._lastInput=b;a.timepicker._setTimeFromField(c);a.timepicker._inDialog&&(b.value="");a.timepicker._pos||(a.timepicker._pos=a.timepicker._findPos(b),
a.timepicker._pos[1]+=b.offsetHeight);var h=!1;a(b).parents().each(function(){h|="fixed"==a(this).css("position");return!h});e={left:a.timepicker._pos[0],top:a.timepicker._pos[1]};a.timepicker._pos=null;c.tpDiv.css({position:"absolute",display:"block",top:"-1000px"});a.timepicker._updateTimepicker(c);c.inline||"object"!=typeof a.ui.position||(c.tpDiv.position({of:c.input,my:a.timepicker._get(c,"myPosition"),at:a.timepicker._get(c,"atPosition"),collision:"flip"}),e=c.tpDiv.offset(),a.timepicker._pos=
[e.top,e.left]);c._hoursClicked=!1;c._minutesClicked=!1;e=a.timepicker._checkOffset(c,e,h);c.tpDiv.css({position:a.timepicker._inDialog&&a.blockUI?"static":h?"fixed":"absolute",display:"none",left:e.left+"px",top:e.top+"px"});if(!c.inline){var e=a.timepicker._get(c,"showAnim"),l=a.timepicker._get(c,"duration"),n=function(){a.timepicker._timepickerShowing=!0;var b=a.timepicker._getBorders(c.tpDiv);c.tpDiv.find("iframe.ui-timepicker-cover").css({left:-b[0],top:-b[1],width:c.tpDiv.outerWidth(),height:c.tpDiv.outerHeight()})};
a.timepicker._adjustZIndex(b);a.effects&&a.effects[e]?c.tpDiv.show(e,a.timepicker._get(c,"showOptions"),l,n):c.tpDiv.show(e?l:null,n);e&&l||n();c.input.is(":visible")&&!c.input.is(":disabled")&&c.input.focus();a.timepicker._curInst=c}}},_getZIndex:function(b){b=a(b);for(var c=0,e;b.length&&b[0]!==document;){e=b.css("position");if("absolute"===e||"relative"===e||"fixed"===e)e=parseInt(b.css("zIndex"),10),isNaN(e)||0===e||e>c&&(c=e);b=b.parent()}return c},_refreshTimepicker:function(b){(b=this._getInst(b))&&
this._updateTimepicker(b)},_updateTimepicker:function(b){b.tpDiv.empty().append(this._generateHTML(b));this._rebindDialogEvents(b)},_rebindDialogEvents:function(b){var c=a.timepicker._getBorders(b.tpDiv),e=this;b.tpDiv.find("iframe.ui-timepicker-cover").css({left:-c[0],top:-c[1],width:b.tpDiv.outerWidth(),height:b.tpDiv.outerHeight()}).end().find(".ui-timepicker-minute-cell").unbind().bind("click",{fromDoubleClick:!1},a.proxy(a.timepicker.selectMinutes,this)).bind("dblclick",{fromDoubleClick:!0},
a.proxy(a.timepicker.selectMinutes,this)).end().find(".ui-timepicker-hour-cell").unbind().bind("click",{fromDoubleClick:!1},a.proxy(a.timepicker.selectHours,this)).bind("dblclick",{fromDoubleClick:!0},a.proxy(a.timepicker.selectHours,this)).end().find(".ui-timepicker td a").unbind().bind("mouseout",function(){a(this).removeClass("ui-state-hover");-1!=this.className.indexOf("ui-timepicker-prev")&&a(this).removeClass("ui-timepicker-prev-hover");-1!=this.className.indexOf("ui-timepicker-next")&&a(this).removeClass("ui-timepicker-next-hover")}).bind("mouseover",
function(){e._isDisabledTimepicker(b.inline?b.tpDiv.parent()[0]:b.input[0])||(a(this).parents(".ui-timepicker-calendar").find("a").removeClass("ui-state-hover"),a(this).addClass("ui-state-hover"),-1!=this.className.indexOf("ui-timepicker-prev")&&a(this).addClass("ui-timepicker-prev-hover"),-1!=this.className.indexOf("ui-timepicker-next")&&a(this).addClass("ui-timepicker-next-hover"))}).end().find("."+this._dayOverClass+" a").trigger("mouseover").end().find(".ui-timepicker-now").bind("click",function(b){a.timepicker.selectNow(b)}).end().find(".ui-timepicker-deselect").bind("click",
function(b){a.timepicker.deselectTime(b)}).end().find(".ui-timepicker-close").bind("click",function(b){a.timepicker._hideTimepicker()}).end()},_generateHTML:function(b){var a,e,h,d,n=1==this._get(b,"showPeriod"),g=1==this._get(b,"showPeriodLabels"),f=1==this._get(b,"showLeadingZero");e=1==this._get(b,"showHours");var m=1==this._get(b,"showMinutes"),p=this._get(b,"amPmText"),q=this._get(b,"rows"),t=0,u=0,x=d=0,z=0,y=0,v=[],A=this._get(b,"hours");a=null;var w=0;h=this._get(b,"hourText");var B=this._get(b,
"showCloseButton"),E=this._get(b,"closeButtonText"),C=this._get(b,"showNowButton"),F=this._get(b,"nowButtonText"),D=this._get(b,"showDeselectButton"),G=this._get(b,"deselectButtonText"),H=B||C||D;for(a=A.starts;a<=A.ends;a++)v.push(a);a=Math.ceil(v.length/q);if(g){for(w=0;w<v.length;w++)12>v[w]?d++:x++;w=0;t=Math.floor(d/v.length*q);u=Math.floor(x/v.length*q);q!=t+u&&(d&&(!x||!t||u&&d/t>=x/u)?t++:u++);z=Math.min(t,1);y=t+1;a=0==t?Math.ceil(x/u):0==u?Math.ceil(d/t):Math.ceil(Math.max(d/t,x/u))}d='<table class="ui-timepicker-table ui-widget-content ui-corner-all"><tr>';
if(e){d+='<td class="ui-timepicker-hours"><div class="ui-timepicker-title ui-widget-header ui-helper-clearfix ui-corner-all">'+h+'</div><table class="ui-timepicker">';for(e=1;e<=q;e++){d+="<tr>";e==z&&g&&(d+='<th rowspan="'+t.toString()+'" class="periods" scope="row">'+p[0]+"</th>");e==y&&g&&(d+='<th rowspan="'+u.toString()+'" class="periods" scope="row">'+p[1]+"</th>");for(h=1;h<=a;h++)g&&e<y&&12<=v[w]?d+=this._generateHTMLHourCell(b,void 0,n,f):(d+=this._generateHTMLHourCell(b,v[w],n,f),w++);d+=
"</tr>"}d+="</table></td>"}m&&(d=d+'<td class="ui-timepicker-minutes">'+this._generateHTMLMinutes(b),d+="</td>");d+="</tr>";H&&(n='<tr><td colspan="3"><div class="ui-timepicker-buttonpane ui-widget-content">',C&&(n+='<button type="button" class="ui-timepicker-now ui-state-default ui-corner-all"  data-timepicker-instance-id="#'+b.id.replace(/\\\\/g,"\\")+'" >'+F+"</button>"),D&&(n+='<button type="button" class="ui-timepicker-deselect ui-state-default ui-corner-all"  data-timepicker-instance-id="#'+
b.id.replace(/\\\\/g,"\\")+'" >'+G+"</button>"),B&&(n+='<button type="button" class="ui-timepicker-close ui-state-default ui-corner-all"  data-timepicker-instance-id="#'+b.id.replace(/\\\\/g,"\\")+'" >'+E+"</button>"),d+=n+"</div></td></tr>");return d+="</table>"},_updateMinuteDisplay:function(b){var a=this._generateHTMLMinutes(b);b.tpDiv.find("td.ui-timepicker-minutes").html(a);this._rebindDialogEvents(b)},_generateHTMLMinutes:function(b){var c,e,h="",d=this._get(b,"rows"),n=[];e=this._get(b,"minutes");
var g=null,f=0,m=1==this._get(b,"showMinutesLeadingZero"),p=this._get(b,"onMinuteShow"),q=this._get(b,"minuteText");e.starts||(e.starts=0);e.ends||(e.ends=59);e.manual||(e.manual=[]);for(c=e.starts;c<=e.ends;c+=e.interval)n.push(c);for(i=0;i<e.manual.length;i++)c=e.manual[i],"number"!=typeof c||0>c||59<c||0<=a.inArray(c,n)||n.push(c);n.sort(function(b,a){return b-a});g=Math.round(n.length/d+.49);if(p&&0==p.apply(b.input?b.input[0]:null,[b.hours,b.minutes]))for(f=0;f<n.length;f+=1)if(c=n[f],p.apply(b.input?
b.input[0]:null,[b.hours,c])){b.minutes=c;break}h+='<div class="ui-timepicker-title ui-widget-header ui-helper-clearfix ui-corner-all">'+q+'</div><table class="ui-timepicker">';f=0;for(e=1;e<=d;e++){for(h+="<tr>";f<e*g;)c=n[f],p="",void 0!==c&&(p=10>c&&m?"0"+c.toString():c.toString()),h+=this._generateHTMLMinuteCell(b,c,p),f++;h+="</tr>"}return h+"</table>"},_generateHTMLHourCell:function(b,a,e,h){var d=a;12<a&&e&&(d=a-12);0==d&&e&&(d=12);10>d&&h&&(d="0"+d);e="";e=!0;h=this._get(b,"onHourShow");var n=
this._get(b,"maxTime"),g=this._get(b,"minTime");if(void 0==a)return'<td><span class="ui-state-default ui-state-disabled">&nbsp;</span></td>';h&&(e=h.apply(b.input?b.input[0]:null,[a]));e&&(!isNaN(parseInt(n.hour))&&a>n.hour&&(e=!1),!isNaN(parseInt(g.hour))&&a<g.hour&&(e=!1));return e=e?'<td class="ui-timepicker-hour-cell" data-timepicker-instance-id="#'+b.id.replace(/\\\\/g,"\\")+'" data-hour="'+a.toString()+'"><a class="ui-state-default '+(a==b.hours?"ui-state-active":"")+'">'+d.toString()+"</a></td>":
'<td><span class="ui-state-default ui-state-disabled '+(a==b.hours?" ui-state-active ":" ")+'">'+d.toString()+"</span></td>"},_generateHTMLMinuteCell:function(b,a,e){var h="",h=!0,d=b.hours,g=this._get(b,"onMinuteShow"),f=this._get(b,"maxTime"),k=this._get(b,"minTime");g&&(h=g.apply(b.input?b.input[0]:null,[b.hours,a]));if(void 0==a)return'<td><span class="ui-state-default ui-state-disabled">&nbsp;</span></td>';h&&null!==d&&(!isNaN(parseInt(f.hour))&&!isNaN(parseInt(f.minute))&&d>=f.hour&&a>f.minute&&
(h=!1),!isNaN(parseInt(k.hour))&&!isNaN(parseInt(k.minute))&&d<=k.hour&&a<k.minute&&(h=!1));return h=h?'<td class="ui-timepicker-minute-cell" data-timepicker-instance-id="#'+b.id.replace(/\\\\/g,"\\")+'" data-minute="'+a.toString()+'" ><a class="ui-state-default '+(a==b.minutes?"ui-state-active":"")+'" >'+e+"</a></td>":'<td><span class="ui-state-default ui-state-disabled" >'+e+"</span></td>"},_destroyTimepicker:function(b){var c=a(b),e=a.data(b,"timepicker");if(c.hasClass(this.markerClassName)){var h=
b.nodeName.toLowerCase();a.removeData(b,"timepicker");"input"==h?(e.append.remove(),e.trigger.remove(),c.removeClass(this.markerClassName).unbind("focus.timepicker",this._showTimepicker).unbind("click.timepicker",this._adjustZIndex)):"div"!=h&&"span"!=h||c.removeClass(this.markerClassName).empty()}},_enableTimepicker:function(b){var c=a(b),e=c.attr("id"),h=a.data(b,"timepicker");if(c.hasClass(this.markerClassName)){var d=b.nodeName.toLowerCase();if("input"==d)b.disabled=!1,b=this._get(h,"button"),
a(b).removeClass("ui-state-disabled").disabled=!1,h.trigger.filter("button").each(function(){this.disabled=!1}).end();else if("div"==d||"span"==d)h=c.children("."+this._inlineClass),h.children().removeClass("ui-state-disabled"),h.find("button").each(function(){this.disabled=!1});this._disabledInputs=a.map(this._disabledInputs,function(b){return b==e?null:b})}},_disableTimepicker:function(b){var c=a(b),e=a.data(b,"timepicker");if(c.hasClass(this.markerClassName)){var h=b.nodeName.toLowerCase();if("input"==
h)h=this._get(e,"button"),a(h).addClass("ui-state-disabled").disabled=!0,b.disabled=!0,e.trigger.filter("button").each(function(){this.disabled=!0}).end();else if("div"==h||"span"==h)e=c.children("."+this._inlineClass),e.children().addClass("ui-state-disabled"),e.find("button").each(function(){this.disabled=!0});this._disabledInputs=a.map(this._disabledInputs,function(a){return a==b?null:a});this._disabledInputs[this._disabledInputs.length]=c.attr("id")}},_isDisabledTimepicker:function(b){if(!b)return!1;
for(var a=0;a<this._disabledInputs.length;a++)if(this._disabledInputs[a]==b)return!0;return!1},_checkOffset:function(b,c,e){var h=b.tpDiv.outerWidth(),d=b.tpDiv.outerHeight(),g=b.input?b.input.outerWidth():0,f=b.input?b.input.outerHeight():0,k=document.documentElement.clientWidth+a(document).scrollLeft(),m=document.documentElement.clientHeight+a(document).scrollTop();c.left-=this._get(b,"isRTL")?h-g:0;c.left-=e&&c.left==b.input.offset().left?a(document).scrollLeft():0;c.top-=e&&c.top==b.input.offset().top+
f?a(document).scrollTop():0;c.left-=Math.min(c.left,c.left+h>k&&k>h?Math.abs(c.left+h-k):0);c.top-=Math.min(c.top,c.top+d>m&&m>d?Math.abs(d+f):0);return c},_findPos:function(b){for(var c=this._getInst(b),c=this._get(c,"isRTL");b&&("hidden"==b.type||1!=b.nodeType);)b=b[c?"previousSibling":"nextSibling"];b=a(b).offset();return[b.left,b.top]},_getBorders:function(b){var a=function(b){return{thin:1,medium:2,thick:3}[b]||b};return[parseFloat(a(b.css("border-left-width"))),parseFloat(a(b.css("border-top-width")))]},
_checkExternalClick:function(b){a.timepicker._curInst&&(b=a(b.target),b[0].id==a.timepicker._mainDivId||0!=b.parents("#"+a.timepicker._mainDivId).length||b.hasClass(a.timepicker.markerClassName)||b.hasClass(a.timepicker._triggerClass)||!a.timepicker._timepickerShowing||a.timepicker._inDialog&&a.blockUI||a.timepicker._hideTimepicker())},_hideTimepicker:function(b){var c=this._curInst;if(c&&(!b||c==a.data(b,"timepicker"))&&this._timepickerShowing){b=this._get(c,"showAnim");var e=this._get(c,"duration"),
h=function(){a.timepicker._tidyDialog(c);this._curInst=null};if(a.effects&&a.effects[b])c.tpDiv.hide(b,a.timepicker._get(c,"showOptions"),e,h);else c.tpDiv["slideDown"==b?"slideUp":"fadeIn"==b?"fadeOut":"hide"](b?e:null,h);b||h();this._timepickerShowing=!1;this._lastInput=null;this._inDialog&&(this._dialogInput.css({position:"absolute",left:"0",top:"-100px"}),a.blockUI&&(a.unblockUI(),a("body").append(this.tpDiv)));this._inDialog=!1;(b=this._get(c,"onClose"))&&b.apply(c.input?c.input[0]:null,[c.input?
c.input.val():"",c])}},_tidyDialog:function(b){b.tpDiv.removeClass(this._dialogClass).unbind(".ui-timepicker")},_getInst:function(b){try{return a.data(b,"timepicker")}catch(c){throw"Missing instance data for this timepicker";}},_get:function(b,a){return void 0!==b.settings[a]?b.settings[a]:this._defaults[a]},_setTimeFromField:function(b){if(b.input.val()!=b.lastVal){var c=this._get(b,"defaultTime"),c="now"==c?this._getCurrentTimeRounded(b):c;0==b.inline&&""!=b.input.val()&&(c=b.input.val());if(c instanceof
Date)b.hours=c.getHours(),b.minutes=c.getMinutes();else{var e=b.lastVal=c;""==c?(b.hours=-1,b.minutes=-1):(c=this.parseTime(b,e),b.hours=c.hours,b.minutes=c.minutes)}a.timepicker._updateTimepicker(b)}},_optionTimepicker:function(b,c,e){var h=this._getInst(b);if(2==arguments.length&&"string"==typeof c)return"defaults"==c?a.extend({},a.timepicker._defaults):h?"all"==c?a.extend({},h.settings):this._get(h,c):null;var g=c||{};"string"==typeof c&&(g={},g[c]=e);h&&(d(h.settings,g),this._curInst==h&&(this._hideTimepicker(),
this._updateTimepicker(h)),h.inline&&this._updateTimepicker(h))},_setTimeTimepicker:function(b,a){var e=this._getInst(b);e&&(this._setTime(e,a),this._updateTimepicker(e),this._updateAlternate(e,a))},_setTime:function(b,a,e){var h=b.hours,d=b.minutes;a instanceof Date?(b.hours=a.getHours(),b.minutes=a.getMinutes()):(a=this.parseTime(b,a),b.hours=a.hours,b.minutes=a.minutes);h==b.hours&&d==b.minutes||e||b.input.trigger("change");this._updateTimepicker(b);this._updateSelectedValue(b)},_getCurrentTimeRounded:function(b){var a=
new Date,e=a.getMinutes();b=this._get(b,"minutes");e=Math.round(e/b.interval)*b.interval;a.setMinutes(e);return a},parseTime:function(b,a){var e={hours:-1,minutes:-1};if(!a)return"";var h=this._get(b,"timeSeparator"),d=this._get(b,"amPmText"),g=this._get(b,"showHours"),f=this._get(b,"showMinutes"),k=this._get(b,"optionalMinutes"),m=1==this._get(b,"showPeriod"),h=a.indexOf(h);-1!=h?(e.hours=parseInt(a.substr(0,h),10),e.minutes=parseInt(a.substr(h+1),10)):!g||f&&!k?!g&&f&&(e.minutes=parseInt(a,10)):
e.hours=parseInt(a,10);g&&(g=a.toUpperCase(),12>e.hours&&m&&-1!=g.indexOf(d[1].toUpperCase())&&(e.hours+=12),12==e.hours&&m&&-1!=g.indexOf(d[0].toUpperCase())&&(e.hours=0));return e},selectNow:function(b){b=a(b.target).attr("data-timepicker-instance-id");b=a(b);b=this._getInst(b[0]);var c=new Date;b.hours=c.getHours();b.minutes=c.getMinutes();this._updateSelectedValue(b);this._updateTimepicker(b);this._hideTimepicker()},deselectTime:function(b){b=a(b.target).attr("data-timepicker-instance-id");b=
a(b);b=this._getInst(b[0]);b.hours=-1;b.minutes=-1;this._updateSelectedValue(b);this._hideTimepicker()},selectHours:function(b){var c=a(b.currentTarget),e=c.attr("data-timepicker-instance-id"),h=parseInt(c.attr("data-hour"));b=b.data.fromDoubleClick;var d=a(e),e=this._getInst(d[0]),g=1==this._get(e,"showMinutes");if(a.timepicker._isDisabledTimepicker(d.attr("id")))return!1;c.parents(".ui-timepicker-hours:first").find("a").removeClass("ui-state-active");c.children("a").addClass("ui-state-active");
e.hours=h;c=this._get(e,"onMinuteShow");h=this._get(e,"maxTime");d=this._get(e,"minTime");(c||h.minute||d.minute)&&this._updateMinuteDisplay(e);this._updateSelectedValue(e);e._hoursClicked=!0;(e._minutesClicked||b||0==g)&&a.timepicker._hideTimepicker();return!1},selectMinutes:function(b){var c=a(b.currentTarget),e=c.attr("data-timepicker-instance-id"),h=parseInt(c.attr("data-minute"));b=b.data.fromDoubleClick;var e=a(e),d=this._getInst(e[0]),g=1==this._get(d,"showHours");if(a.timepicker._isDisabledTimepicker(e.attr("id")))return!1;
c.parents(".ui-timepicker-minutes:first").find("a").removeClass("ui-state-active");c.children("a").addClass("ui-state-active");d.minutes=h;this._updateSelectedValue(d);d._minutesClicked=!0;(d._hoursClicked||b||0==g)&&a.timepicker._hideTimepicker();return!1},_updateSelectedValue:function(b){var a=this._getParsedTime(b);b.input&&(b.input.val(a),b.input.trigger("change"));var e=this._get(b,"onSelect");e&&e.apply(b.input?b.input[0]:null,[a,b]);this._updateAlternate(b,a);return a},_getParsedTime:function(b){if(-1==
b.hours&&-1==b.minutes)return"";if(b.hours<b.hours.starts||b.hours>b.hours.ends)b.hours=0;if(b.minutes<b.minutes.starts||b.minutes>b.minutes.ends)b.minutes=0;var a="",e=1==this._get(b,"showPeriod"),h=1==this._get(b,"showLeadingZero"),d=1==this._get(b,"showHours"),g=1==this._get(b,"showMinutes"),f=1==this._get(b,"optionalMinutes"),k=this._get(b,"amPmText"),m=b.hours?b.hours:0,p=b.minutes?b.minutes:0,q=m?m:0,m="";-1==q&&(q=0);-1==p&&(p=0);e&&(0==b.hours&&(q=12),12>b.hours?a=k[0]:(a=k[1],12<q&&(q-=12)));
e=q.toString();h&&10>q&&(e="0"+e);h=p.toString();10>p&&(h="0"+h);d&&(m+=e);!d||!g||f&&0==h||(m+=this._get(b,"timeSeparator"));!g||f&&0==h||(m+=h);d&&0<a.length&&(m+=this._get(b,"periodSeparator")+a);return m},_updateAlternate:function(b,c){var e=this._get(b,"altField");e&&a(e).each(function(b,e){a(e).val(c)})},_getTimeAsDateTimepicker:function(b){b=this._getInst(b);if(-1==b.hours&&-1==b.minutes)return"";if(b.hours<b.hours.starts||b.hours>b.hours.ends)b.hours=0;if(b.minutes<b.minutes.starts||b.minutes>
b.minutes.ends)b.minutes=0;return new Date(0,0,0,b.hours,b.minutes,0)},_getTimeTimepicker:function(b){b=this._getInst(b);return this._getParsedTime(b)},_getHourTimepicker:function(b){b=this._getInst(b);return void 0==b?-1:b.hours},_getMinuteTimepicker:function(b){b=this._getInst(b);return void 0==b?-1:b.minutes}});a.fn.timepicker=function(b){a.timepicker.initialized||(a(document).mousedown(a.timepicker._checkExternalClick),a.timepicker.initialized=!0);0===a("#"+a.timepicker._mainDivId).length&&a("body").append(a.timepicker.tpDiv);
var c=Array.prototype.slice.call(arguments,1);return"string"==typeof b&&("getTime"==b||"getTimeAsDate"==b||"getHour"==b||"getMinute"==b)||"option"==b&&2==arguments.length&&"string"==typeof arguments[1]?a.timepicker["_"+b+"Timepicker"].apply(a.timepicker,[this[0]].concat(c)):this.each(function(){"string"==typeof b?a.timepicker["_"+b+"Timepicker"].apply(a.timepicker,[this].concat(c)):a.timepicker._attachTimepicker(this,b)})};a.timepicker=new f;a.timepicker.initialized=!1;a.timepicker.uuid=(new Date).getTime();
a.timepicker.version="0.3.3";window["TP_jQuery_"+g]=a})(jQuery);!function(a){function f(b,a){if(!(1<b.originalEvent.touches.length)){b.preventDefault();var c=b.originalEvent.changedTouches[0],d=document.createEvent("MouseEvents");d.initMouseEvent(a,!0,!0,window,1,c.screenX,c.screenY,c.clientX,c.clientY,!1,!1,!1,!1,0,null);b.target.dispatchEvent(d)}}if(a.support.touch="ontouchend"in document,a.support.touch){var d,g=a.ui.mouse.prototype,b=g._mouseInit,c=g._mouseDestroy;g._touchStart=function(b){!d&&this._mouseCapture(b.originalEvent.changedTouches[0])&&(d=!0,this._touchMoved=
!1,f(b,"mouseover"),f(b,"mousemove"),f(b,"mousedown"))};g._touchMove=function(b){d&&(this._touchMoved=!0,f(b,"mousemove"))};g._touchEnd=function(b){d&&(f(b,"mouseup"),f(b,"mouseout"),this._touchMoved||f(b,"click"),d=!1)};g._mouseInit=function(){this.element.bind({touchstart:a.proxy(this,"_touchStart"),touchmove:a.proxy(this,"_touchMove"),touchend:a.proxy(this,"_touchEnd")});b.call(this)};g._mouseDestroy=function(){this.element.unbind({touchstart:a.proxy(this,"_touchStart"),touchmove:a.proxy(this,
"_touchMove"),touchend:a.proxy(this,"_touchEnd")});c.call(this)}}}(jQuery);(function(a){"function"===typeof define&&define.amd?define("pnotify",["jquery"],a):a(jQuery)})(function(a){var f={dir1:"down",dir2:"left",push:"bottom",spacing1:25,spacing2:25,context:a("body")},d,g,b=a(window),c=function(){g=a("body");PNotify.prototype.options.stack.context=g;b=a(window);b.bind("resize",function(){d&&clearTimeout(d);d=setTimeout(function(){PNotify.positionAll(!0)},10)})};PNotify=function(b){this.parseOptions(b);this.init()};a.extend(PNotify.prototype,{version:"2.0.1",options:{title:!1,
title_escape:!1,text:!1,text_escape:!1,styling:"bootstrap3",addclass:"",cornerclass:"",auto_display:!0,width:"300px",min_height:"16px",type:"notice",icon:!0,opacity:1,animation:"fade",animate_speed:"slow",position_animate_speed:500,shadow:!0,hide:!0,delay:8E3,mouse_reset:!0,remove:!0,insert_brs:!0,destroy:!0,stack:f},modules:{},runModules:function(b,a){var c,d;for(d in this.modules)if(c="object"===typeof a&&d in a?a[d]:a,"function"===typeof this.modules[d][b])this.modules[d][b](this,"object"===typeof this.options[d]?
this.options[d]:{},c)},state:"initializing",timer:null,styles:null,elem:null,container:null,title_container:null,text_container:null,animating:!1,timerHide:!1,init:function(){var b=this;this.modules={};a.extend(!0,this.modules,PNotify.prototype.modules);this.styles="object"===typeof this.options.styling?this.options.styling:PNotify.styling[this.options.styling];this.elem=a("<div />",{"class":"ui-pnotify "+this.options.addclass,css:{display:"none"},mouseenter:function(a){if(b.options.mouse_reset&&
"out"===b.animating){if(!b.timerHide)return;b.cancelRemove()}b.options.hide&&b.options.mouse_reset&&b.cancelRemove()},mouseleave:function(a){b.options.hide&&b.options.mouse_reset&&b.queueRemove();PNotify.positionAll()}});this.container=a("<div />",{"class":this.styles.container+" ui-pnotify-container "+("error"===this.options.type?this.styles.error:"info"===this.options.type?this.styles.info:"success"===this.options.type?this.styles.success:this.styles.notice)}).appendTo(this.elem);""!==this.options.cornerclass&&
this.container.removeClass("ui-corner-all").addClass(this.options.cornerclass);this.options.shadow&&this.container.addClass("ui-pnotify-shadow");!1!==this.options.icon&&a("<div />",{"class":"ui-pnotify-icon"}).append(a("<span />",{"class":!0===this.options.icon?"error"===this.options.type?this.styles.error_icon:"info"===this.options.type?this.styles.info_icon:"success"===this.options.type?this.styles.success_icon:this.styles.notice_icon:this.options.icon})).prependTo(this.container);this.title_container=
a("<h4 />",{"class":"ui-pnotify-title"}).appendTo(this.container);!1===this.options.title?this.title_container.hide():this.options.title_escape?this.title_container.text(this.options.title):this.title_container.html(this.options.title);this.text_container=a("<div />",{"class":"ui-pnotify-text"}).appendTo(this.container);!1===this.options.text?this.text_container.hide():this.options.text_escape?this.text_container.text(this.options.text):this.text_container.html(this.options.insert_brs?String(this.options.text).replace(/\n/g,
"<br />"):this.options.text);"string"===typeof this.options.width&&this.elem.css("width",this.options.width);"string"===typeof this.options.min_height&&this.container.css("min-height",this.options.min_height);PNotify.notices="top"===this.options.stack.push?a.merge([this],PNotify.notices):a.merge(PNotify.notices,[this]);"top"===this.options.stack.push&&this.queuePosition(!1,1);this.options.stack.animation=!1;this.runModules("init");this.options.auto_display&&this.open();return this},update:function(b){var c=
this.options;this.parseOptions(c,b);this.options.cornerclass!==c.cornerclass&&this.container.removeClass("ui-corner-all "+c.cornerclass).addClass(this.options.cornerclass);this.options.shadow!==c.shadow&&(this.options.shadow?this.container.addClass("ui-pnotify-shadow"):this.container.removeClass("ui-pnotify-shadow"));!1===this.options.addclass?this.elem.removeClass(c.addclass):this.options.addclass!==c.addclass&&this.elem.removeClass(c.addclass).addClass(this.options.addclass);!1===this.options.title?
this.title_container.slideUp("fast"):this.options.title!==c.title&&(this.options.title_escape?this.title_container.text(this.options.title):this.title_container.html(this.options.title),!1===c.title&&this.title_container.slideDown(200));!1===this.options.text?this.text_container.slideUp("fast"):this.options.text!==c.text&&(this.options.text_escape?this.text_container.text(this.options.text):this.text_container.html(this.options.insert_brs?String(this.options.text).replace(/\n/g,"<br />"):this.options.text),
!1===c.text&&this.text_container.slideDown(200));this.options.type!==c.type&&this.container.removeClass(this.styles.error+" "+this.styles.notice+" "+this.styles.success+" "+this.styles.info).addClass("error"===this.options.type?this.styles.error:"info"===this.options.type?this.styles.info:"success"===this.options.type?this.styles.success:this.styles.notice);if(this.options.icon!==c.icon||!0===this.options.icon&&this.options.type!==c.type)this.container.find("div.ui-pnotify-icon").remove(),!1!==this.options.icon&&
a("<div />",{"class":"ui-pnotify-icon"}).append(a("<span />",{"class":!0===this.options.icon?"error"===this.options.type?this.styles.error_icon:"info"===this.options.type?this.styles.info_icon:"success"===this.options.type?this.styles.success_icon:this.styles.notice_icon:this.options.icon})).prependTo(this.container);this.options.width!==c.width&&this.elem.animate({width:this.options.width});this.options.min_height!==c.min_height&&this.container.animate({minHeight:this.options.min_height});this.options.opacity!==
c.opacity&&this.elem.fadeTo(this.options.animate_speed,this.options.opacity);this.options.hide?c.hide||this.queueRemove():this.cancelRemove();this.queuePosition(!0);this.runModules("update",c);return this},open:function(){this.state="opening";this.runModules("beforeOpen");var b=this;this.elem.parent().length||this.elem.appendTo(this.options.stack.context?this.options.stack.context:g);"top"!==this.options.stack.push&&this.position(!0);"fade"===this.options.animation||"fade"===this.options.animation.effect_in?
this.elem.show().fadeTo(0,0).hide():1!==this.options.opacity&&this.elem.show().fadeTo(0,this.options.opacity).hide();this.animateIn(function(){b.queuePosition(!0);b.options.hide&&b.queueRemove();b.state="open";b.runModules("afterOpen")});return this},remove:function(b){this.state="closing";this.timerHide=!!b;this.runModules("beforeClose");var c=this;this.timer&&(window.clearTimeout(this.timer),this.timer=null);this.animateOut(function(){c.state="closed";c.runModules("afterClose");c.queuePosition(!0);
c.options.remove&&c.elem.detach();c.runModules("beforeDestroy");if(c.options.destroy&&null!==PNotify.notices){var b=a.inArray(c,PNotify.notices);-1!==b&&PNotify.notices.splice(b,1)}c.runModules("afterDestroy")});return this},get:function(){return this.elem},parseOptions:function(b,c){this.options=a.extend(!0,{},PNotify.prototype.options);this.options.stack=PNotify.prototype.options.stack;var d=[b,c],g,f;for(f in d){g=d[f];if("undefined"==typeof g)break;if("object"!==typeof g)this.options.text=g;else for(var k in g)this.modules[k]?
a.extend(!0,this.options[k],g[k]):this.options[k]=g[k]}},animateIn:function(b){this.animating="in";var a;a="undefined"!==typeof this.options.animation.effect_in?this.options.animation.effect_in:this.options.animation;"none"===a?(this.elem.show(),b()):"show"===a?this.elem.show(this.options.animate_speed,b):"fade"===a?this.elem.show().fadeTo(this.options.animate_speed,this.options.opacity,b):"slide"===a?this.elem.slideDown(this.options.animate_speed,b):"function"===typeof a?a("in",b,this.elem):this.elem.show(a,
"object"===typeof this.options.animation.options_in?this.options.animation.options_in:{},this.options.animate_speed,b);this.elem.parent().hasClass("ui-effects-wrapper")&&this.elem.parent().css({position:"fixed",overflow:"visible"});"slide"!==a&&this.elem.css("overflow","visible");this.container.css("overflow","hidden")},animateOut:function(b){this.animating="out";var a;a="undefined"!==typeof this.options.animation.effect_out?this.options.animation.effect_out:this.options.animation;"none"===a?(this.elem.hide(),
b()):"show"===a?this.elem.hide(this.options.animate_speed,b):"fade"===a?this.elem.fadeOut(this.options.animate_speed,b):"slide"===a?this.elem.slideUp(this.options.animate_speed,b):"function"===typeof a?a("out",b,this.elem):this.elem.hide(a,"object"===typeof this.options.animation.options_out?this.options.animation.options_out:{},this.options.animate_speed,b);this.elem.parent().hasClass("ui-effects-wrapper")&&this.elem.parent().css({position:"fixed",overflow:"visible"});"slide"!==a&&this.elem.css("overflow",
"visible");this.container.css("overflow","hidden")},position:function(a){var c=this.options.stack,d=this.elem;d.parent().hasClass("ui-effects-wrapper")&&(d=this.elem.css({left:"0",top:"0",right:"0",bottom:"0"}).parent());"undefined"===typeof c.context&&(c.context=g);if(c){"number"!==typeof c.nextpos1&&(c.nextpos1=c.firstpos1);"number"!==typeof c.nextpos2&&(c.nextpos2=c.firstpos2);"number"!==typeof c.addpos2&&(c.addpos2=0);var f="none"===d.css("display");if(!f||a){var r,k={},m;switch(c.dir1){case "down":m=
"top";break;case "up":m="bottom";break;case "left":m="right";break;case "right":m="left"}a=parseInt(d.css(m).replace(/(?:\..*|[^0-9.])/g,""));isNaN(a)&&(a=0);"undefined"!==typeof c.firstpos1||f||(c.firstpos1=a,c.nextpos1=c.firstpos1);var p;switch(c.dir2){case "down":p="top";break;case "up":p="bottom";break;case "left":p="right";break;case "right":p="left"}r=parseInt(d.css(p).replace(/(?:\..*|[^0-9.])/g,""));isNaN(r)&&(r=0);"undefined"!==typeof c.firstpos2||f||(c.firstpos2=r,c.nextpos2=c.firstpos2);
if("down"===c.dir1&&c.nextpos1+d.height()>(c.context.is(g)?b.height():c.context.prop("scrollHeight"))||"up"===c.dir1&&c.nextpos1+d.height()>(c.context.is(g)?b.height():c.context.prop("scrollHeight"))||"left"===c.dir1&&c.nextpos1+d.width()>(c.context.is(g)?b.width():c.context.prop("scrollWidth"))||"right"===c.dir1&&c.nextpos1+d.width()>(c.context.is(g)?b.width():c.context.prop("scrollWidth")))c.nextpos1=c.firstpos1,c.nextpos2+=c.addpos2+("undefined"===typeof c.spacing2?25:c.spacing2),c.addpos2=0;if(c.animation&&
c.nextpos2<r)switch(c.dir2){case "down":k.top=c.nextpos2+"px";break;case "up":k.bottom=c.nextpos2+"px";break;case "left":k.right=c.nextpos2+"px";break;case "right":k.left=c.nextpos2+"px"}else"number"===typeof c.nextpos2&&d.css(p,c.nextpos2+"px");switch(c.dir2){case "down":case "up":d.outerHeight(!0)>c.addpos2&&(c.addpos2=d.height());break;case "left":case "right":d.outerWidth(!0)>c.addpos2&&(c.addpos2=d.width())}if("number"===typeof c.nextpos1)if(c.animation&&(a>c.nextpos1||k.top||k.bottom||k.right||
k.left))switch(c.dir1){case "down":k.top=c.nextpos1+"px";break;case "up":k.bottom=c.nextpos1+"px";break;case "left":k.right=c.nextpos1+"px";break;case "right":k.left=c.nextpos1+"px"}else d.css(m,c.nextpos1+"px");(k.top||k.bottom||k.right||k.left)&&d.animate(k,{duration:this.options.position_animate_speed,queue:!1});switch(c.dir1){case "down":case "up":c.nextpos1+=d.height()+("undefined"===typeof c.spacing1?25:c.spacing1);break;case "left":case "right":c.nextpos1+=d.width()+("undefined"===typeof c.spacing1?
25:c.spacing1)}}return this}},queuePosition:function(b,a){d&&clearTimeout(d);a||(a=10);d=setTimeout(function(){PNotify.positionAll(b)},a);return this},cancelRemove:function(){this.timer&&window.clearTimeout(this.timer);"closing"===this.state&&(this.elem.stop(!0),this.state="open",this.animating="in",this.elem.css("height","auto").animate({width:this.options.width,opacity:this.options.opacity},"fast"));return this},queueRemove:function(){var b=this;this.cancelRemove();this.timer=window.setTimeout(function(){b.remove(!0)},
isNaN(this.options.delay)?0:this.options.delay);return this}});a.extend(PNotify,{notices:[],removeAll:function(){a.each(PNotify.notices,function(){this.remove&&this.remove()})},positionAll:function(b){d&&clearTimeout(d);d=null;a.each(PNotify.notices,function(){var a=this.options.stack;a&&(a.nextpos1=a.firstpos1,a.nextpos2=a.firstpos2,a.addpos2=0,a.animation=b)});a.each(PNotify.notices,function(){this.position()})},styling:{jqueryui:{container:"ui-widget ui-widget-content ui-corner-all",notice:"ui-state-highlight",
notice_icon:"ui-icon ui-icon-info",info:"",info_icon:"ui-icon ui-icon-info",success:"ui-state-default",success_icon:"ui-icon ui-icon-circle-check",error:"ui-state-error",error_icon:"ui-icon ui-icon-alert"},bootstrap2:{container:"alert",notice:"",notice_icon:"icon-exclamation-sign",info:"alert-info",info_icon:"icon-info-sign",success:"alert-success",success_icon:"icon-ok-sign",error:"alert-error",error_icon:"icon-warning-sign"},bootstrap3:{container:"alert",notice:"alert-warning",notice_icon:"glyphicon glyphicon-exclamation-sign",
info:"alert-info",info_icon:"glyphicon glyphicon-info-sign",success:"alert-success",success_icon:"glyphicon glyphicon-ok-sign",error:"alert-danger",error_icon:"glyphicon glyphicon-warning-sign"}}});PNotify.styling.fontawesome=a.extend({},PNotify.styling.bootstrap3);a.extend(PNotify.styling.fontawesome,{notice_icon:"fa fa-exclamation-circle",info_icon:"fa fa-info",success_icon:"fa fa-check",error_icon:"fa fa-warning"});document.body?c():a(c);return PNotify});
(function(a){"function"===typeof define&&define.amd?define("pnotify.buttons",["jquery","pnotify"],a):a(jQuery,PNotify)})(function(a,f){f.prototype.options.buttons={closer:!0,closer_hover:!0,sticker:!0,sticker_hover:!0,labels:{close:"Close",stick:"Stick"}};f.prototype.modules.buttons={myOptions:null,closer:null,sticker:null,init:function(d,g){var b=this;this.myOptions=g;d.elem.on({mouseenter:function(a){!b.myOptions.sticker||d.options.nonblock&&d.options.nonblock.nonblock||b.sticker.trigger("pnotify_icon").css("visibility",
"visible");!b.myOptions.closer||d.options.nonblock&&d.options.nonblock.nonblock||b.closer.css("visibility","visible")},mouseleave:function(a){b.myOptions.sticker_hover&&b.sticker.css("visibility","hidden");b.myOptions.closer_hover&&b.closer.css("visibility","hidden")}});this.sticker=a("<div />",{"class":"ui-pnotify-sticker",css:{cursor:"pointer",visibility:g.sticker_hover?"hidden":"visible"},click:function(){d.options.hide=!d.options.hide;d.options.hide?d.queueRemove():d.cancelRemove();a(this).trigger("pnotify_icon")}}).bind("pnotify_icon",
function(){a(this).children().removeClass(d.styles.pin_up+" "+d.styles.pin_down).addClass(d.options.hide?d.styles.pin_up:d.styles.pin_down)}).append(a("<span />",{"class":d.styles.pin_up,title:g.labels.stick})).prependTo(d.container);(!g.sticker||d.options.nonblock&&d.options.nonblock.nonblock)&&this.sticker.css("display","none");this.closer=a("<div />",{"class":"ui-pnotify-closer",css:{cursor:"pointer",visibility:g.closer_hover?"hidden":"visible"},click:function(){d.remove(!1);b.sticker.css("visibility",
"hidden");b.closer.css("visibility","hidden")}}).append(a("<span />",{"class":d.styles.closer,title:g.labels.close})).prependTo(d.container);(!g.closer||d.options.nonblock&&d.options.nonblock.nonblock)&&this.closer.css("display","none")},update:function(a,g){this.myOptions=g;!g.closer||a.options.nonblock&&a.options.nonblock.nonblock?this.closer.css("display","none"):g.closer&&this.closer.css("display","block");!g.sticker||a.options.nonblock&&a.options.nonblock.nonblock?this.sticker.css("display",
"none"):g.sticker&&this.sticker.css("display","block");this.sticker.trigger("pnotify_icon");g.sticker_hover?this.sticker.css("visibility","hidden"):a.options.nonblock&&a.options.nonblock.nonblock||this.sticker.css("visibility","visible");g.closer_hover?this.closer.css("visibility","hidden"):a.options.nonblock&&a.options.nonblock.nonblock||this.closer.css("visibility","visible")}};a.extend(f.styling.jqueryui,{closer:"ui-icon ui-icon-close",pin_up:"ui-icon ui-icon-pin-w",pin_down:"ui-icon ui-icon-pin-s"});
a.extend(f.styling.bootstrap2,{closer:"icon-remove",pin_up:"icon-pause",pin_down:"icon-play"});a.extend(f.styling.bootstrap3,{closer:"glyphicon glyphicon-remove",pin_up:"glyphicon glyphicon-pause",pin_down:"glyphicon glyphicon-play"});a.extend(f.styling.fontawesome,{closer:"fa fa-times",pin_up:"fa fa-pause",pin_down:"fa fa-play"})});
(function(a){"function"===typeof define&&define.amd?define("pnotify.callbacks",["jquery","pnotify"],a):a(jQuery,PNotify)})(function(a,f){var d=f.prototype.init,g=f.prototype.open,b=f.prototype.remove;f.prototype.init=function(){this.options.before_init&&this.options.before_init(this.options);d.apply(this,arguments);this.options.after_init&&this.options.after_init(this)};f.prototype.open=function(){var b;this.options.before_open&&(b=this.options.before_open(this));!1!==b&&(g.apply(this,arguments),
this.options.after_open&&this.options.after_open(this))};f.prototype.remove=function(a){var d;this.options.before_close&&(d=this.options.before_close(this,a));!1!==d&&(b.apply(this,arguments),this.options.after_close&&this.options.after_close(this,a))}});
(function(a){"function"===typeof define&&define.amd?define("pnotify.confirm",["jquery","pnotify"],a):a(jQuery,PNotify)})(function(a,f){f.prototype.options.confirm={confirm:!1,prompt:!1,prompt_class:"",prompt_default:"",prompt_multi_line:!1,align:"right",buttons:[{text:"Ok",addClass:"",promptTrigger:!0,click:function(a,g){a.remove();a.get().trigger("pnotify.confirm",[a,g])}},{text:"Cancel",addClass:"",click:function(a){a.remove();a.get().trigger("pnotify.cancel",a)}}]};f.prototype.modules.confirm=
{container:null,prompt:null,init:function(d,g){this.container=a('<div style="margin-top:5px;clear:both;" />').css("text-align",g.align).appendTo(d.container);g.confirm||g.prompt?this.makeDialog(d,g):this.container.hide()},update:function(a,g){g.confirm?(this.makeDialog(a,g),this.container.show()):this.container.hide().empty()},afterOpen:function(a,g){g.prompt&&this.prompt.focus()},makeDialog:function(d,g){var b=!1,c=this,e,h;this.container.empty();g.prompt&&(this.prompt=a("<"+(g.prompt_multi_line?
'textarea rows="5"':'input type="text"')+' style="margin-bottom:5px;clear:both;" />').addClass(d.styles.input+" "+g.prompt_class).val(g.prompt_default).appendTo(this.container));for(var f in g.buttons){e=g.buttons[f];b?this.container.append(" "):b=!0;h=a('<button type="button" />').addClass(d.styles.btn+" "+e.addClass).text(e.text).appendTo(this.container).on("click",function(b){return function(){"function"==typeof b.click&&b.click(d,g.prompt?c.prompt.val():null)}}(e));g.prompt&&!g.prompt_multi_line&&
e.promptTrigger&&this.prompt.keypress(function(b){return function(a){13==a.keyCode&&b.click()}}(h));d.styles.text&&h.wrapInner('<span class="'+d.styles.text+'"></span>');d.styles.btnhover&&h.hover(function(b){return function(){b.addClass(d.styles.btnhover)}}(h),function(b){return function(){b.removeClass(d.styles.btnhover)}}(h));if(d.styles.btnactive)h.on("mousedown",function(b){return function(){b.addClass(d.styles.btnactive)}}(h)).on("mouseup",function(b){return function(){b.removeClass(d.styles.btnactive)}}(h));
if(d.styles.btnfocus)h.on("focus",function(b){return function(){b.addClass(d.styles.btnfocus)}}(h)).on("blur",function(b){return function(){b.removeClass(d.styles.btnfocus)}}(h))}}};a.extend(f.styling.jqueryui,{btn:"ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only",btnhover:"ui-state-hover",btnactive:"ui-state-active",btnfocus:"ui-state-focus",input:"",text:"ui-button-text"});a.extend(f.styling.bootstrap2,{btn:"btn",input:""});a.extend(f.styling.bootstrap3,{btn:"btn btn-default",
input:"form-control"});a.extend(f.styling.fontawesome,{btn:"btn btn-default",input:"form-control"})});
(function(a){"function"===typeof define&&define.amd?define("pnotify.desktop",["jquery","pnotify"],a):a(jQuery,PNotify)})(function(a,f){var d,g=function(b,a){g="Notification"in window?function(b,a){return new Notification(b,a)}:"mozNotification"in navigator?function(b,a){return navigator.mozNotification.createNotification(b,a.body,a.icon).show()}:"webkitNotifications"in window?function(b,a){return window.webkitNotifications.createNotification(a.icon,b,a.body)}:function(b,a){return null};return g(b,
a)};f.prototype.options.desktop={desktop:!1,icon:null,tag:null};f.prototype.modules.desktop={tag:null,icon:null,genNotice:function(b,a){this.icon=null===a.icon?"http://sciactive.com/pnotify/includes/desktop/"+b.options.type+".png":!1===a.icon?null:a.icon;if(null===this.tag||null!==a.tag)this.tag=null===a.tag?"PNotify-"+Math.round(1E6*Math.random()):a.tag;b.desktop=g(b.options.title,{icon:this.icon,body:b.options.text,tag:this.tag});"close"in b.desktop||(b.desktop.close=function(){b.desktop.cancel()});
b.desktop.onclick=function(){b.elem.trigger("click")};b.desktop.onclose=function(){"closing"!==b.state&&"closed"!==b.state&&b.remove()}},init:function(b,a){a.desktop&&(d=f.desktop.checkPermission(),0==d&&this.genNotice(b,a))},update:function(b,a,e){0==d&&a.desktop&&this.genNotice(b,a)},beforeOpen:function(b,a){0==d&&a.desktop&&b.elem.css({left:"-10000px",display:"none"})},afterOpen:function(b,a){0==d&&a.desktop&&(b.elem.css({left:"-10000px",display:"none"}),"show"in b.desktop&&b.desktop.show())},
beforeClose:function(b,a){0==d&&a.desktop&&b.elem.css({left:"-10000px",display:"none"})},afterClose:function(b,a){0==d&&a.desktop&&(b.elem.css({left:"-10000px",display:"none"}),b.desktop.close())}};f.desktop={permission:function(){"undefined"!==typeof Notification&&"requestPermission"in Notification?Notification.requestPermission():"webkitNotifications"in window&&window.webkitNotifications.requestPermission()},checkPermission:function(){return"undefined"!==typeof Notification&&"permission"in Notification?
"granted"==Notification.permission?0:1:"webkitNotifications"in window?window.webkitNotifications.checkPermission():1}};d=f.desktop.checkPermission()});
(function(a){"function"===typeof define&&define.amd?define("pnotify.history",["jquery","pnotify"],a):a(jQuery,PNotify)})(function(a,f){var d,g;a(function(){a("body").on("pnotify.history-all",function(){a.each(f.notices,function(){this.modules.history.inHistory&&(this.elem.is(":visible")?this.options.hide&&this.queueRemove():this.open&&this.open())})}).on("pnotify.history-last",function(){var b="top"===f.prototype.options.stack.push,a=b?0:-1,d;do{d=-1===a?f.notices.slice(a):f.notices.slice(a,a+1);
if(!d[0])return!1;a=b?a+1:a-1}while(!d[0].modules.history.inHistory||d[0].elem.is(":visible"));d[0].open&&d[0].open()})});f.prototype.options.history={history:!0,menu:!1,fixed:!0,maxonscreen:Infinity,labels:{redisplay:"Redisplay",all:"All",last:"Last"}};f.prototype.modules.history={inHistory:!1,init:function(b,c){b.options.destroy=!1;this.inHistory=c.history;if(c.menu&&"undefined"===typeof d){d=a("<div />",{"class":"ui-pnotify-history-container "+b.styles.hi_menu,mouseleave:function(){d.animate({top:"-"+
g+"px"},{duration:100,queue:!1})}}).append(a("<div />",{"class":"ui-pnotify-history-header",text:c.labels.redisplay})).append(a("<button />",{"class":"ui-pnotify-history-all "+b.styles.hi_btn,text:c.labels.all,mouseenter:function(){a(this).addClass(b.styles.hi_btnhov)},mouseleave:function(){a(this).removeClass(b.styles.hi_btnhov)},click:function(){a(this).trigger("pnotify.history-all");return!1}})).append(a("<button />",{"class":"ui-pnotify-history-last "+b.styles.hi_btn,text:c.labels.last,mouseenter:function(){a(this).addClass(b.styles.hi_btnhov)},
mouseleave:function(){a(this).removeClass(b.styles.hi_btnhov)},click:function(){a(this).trigger("pnotify.history-last");return!1}})).appendTo("body");var e=a("<span />",{"class":"ui-pnotify-history-pulldown "+b.styles.hi_hnd,mouseenter:function(){d.animate({top:"0"},{duration:100,queue:!1})}}).appendTo(d);console.log(e.offset());g=e.offset().top+2;d.css({top:"-"+g+"px"});c.fixed&&d.addClass("ui-pnotify-history-fixed")}},update:function(b,a){this.inHistory=a.history;a.fixed&&d?d.addClass("ui-pnotify-history-fixed"):
d&&d.removeClass("ui-pnotify-history-fixed")},beforeOpen:function(b,c){if(f.notices&&f.notices.length>c.maxonscreen){var d;d="top"!==b.options.stack.push?f.notices.slice(0,f.notices.length-c.maxonscreen):f.notices.slice(c.maxonscreen,f.notices.length);a.each(d,function(){this.remove&&this.remove()})}}};a.extend(f.styling.jqueryui,{hi_menu:"ui-state-default ui-corner-bottom",hi_btn:"ui-state-default ui-corner-all",hi_btnhov:"ui-state-hover",hi_hnd:"ui-icon ui-icon-grip-dotted-horizontal"});a.extend(f.styling.bootstrap2,
{hi_menu:"well",hi_btn:"btn",hi_btnhov:"",hi_hnd:"icon-chevron-down"});a.extend(f.styling.bootstrap3,{hi_menu:"well",hi_btn:"btn btn-default",hi_btnhov:"",hi_hnd:"glyphicon glyphicon-chevron-down"});a.extend(f.styling.fontawesome,{hi_menu:"well",hi_btn:"btn btn-default",hi_btnhov:"",hi_hnd:"fa fa-chevron-down"})});
(function(a){"function"===typeof define&&define.amd?define("pnotify.nonblock",["jquery","pnotify"],a):a(jQuery,PNotify)})(function(a,f){var d=/^on/,g=/^(dbl)?click$|^mouse(move|down|up|over|out|enter|leave)$|^contextmenu$/,b=/^(focus|blur|select|change|reset)$|^key(press|down|up)$/,c=/^(scroll|resize|(un)?load|abort|error)$/,e=function(e,f){var h;e=e.toLowerCase();document.createEvent&&this.dispatchEvent?(e=e.replace(d,""),e.match(g)?(a(this).offset(),h=document.createEvent("MouseEvents"),h.initMouseEvent(e,
f.bubbles,f.cancelable,f.view,f.detail,f.screenX,f.screenY,f.clientX,f.clientY,f.ctrlKey,f.altKey,f.shiftKey,f.metaKey,f.button,f.relatedTarget)):e.match(b)?(h=document.createEvent("UIEvents"),h.initUIEvent(e,f.bubbles,f.cancelable,f.view,f.detail)):e.match(c)&&(h=document.createEvent("HTMLEvents"),h.initEvent(e,f.bubbles,f.cancelable)),h&&this.dispatchEvent(h)):(e.match(d)||(e="on"+e),h=document.createEventObject(f),this.fireEvent(e,h))},h,l=function(b,c,d){b.elem.css("display","none");var f=document.elementFromPoint(c.clientX,
c.clientY);b.elem.css("display","block");var g=a(f),l=g.css("cursor");b.elem.css("cursor","auto"!==l?l:"default");h&&h.get(0)==f||(h&&(e.call(h.get(0),"mouseleave",c.originalEvent),e.call(h.get(0),"mouseout",c.originalEvent)),e.call(f,"mouseenter",c.originalEvent),e.call(f,"mouseover",c.originalEvent));e.call(f,d,c.originalEvent);h=g};f.prototype.options.nonblock={nonblock:!1,nonblock_opacity:.2};f.prototype.modules.nonblock={myOptions:null,init:function(b,a){var c=this;this.myOptions=a;b.elem.on({mouseenter:function(a){c.myOptions.nonblock&&
a.stopPropagation();c.myOptions.nonblock&&b.elem.stop().animate({opacity:c.myOptions.nonblock_opacity},"fast")},mouseleave:function(a){c.myOptions.nonblock&&a.stopPropagation();h=null;b.elem.css("cursor","auto");c.myOptions.nonblock&&"out"!==b.animating&&b.elem.stop().animate({opacity:b.options.opacity},"fast")},mouseover:function(b){c.myOptions.nonblock&&b.stopPropagation()},mouseout:function(b){c.myOptions.nonblock&&b.stopPropagation()},mousemove:function(a){c.myOptions.nonblock&&(a.stopPropagation(),
l(b,a,"onmousemove"))},mousedown:function(a){c.myOptions.nonblock&&(a.stopPropagation(),a.preventDefault(),l(b,a,"onmousedown"))},mouseup:function(a){c.myOptions.nonblock&&(a.stopPropagation(),a.preventDefault(),l(b,a,"onmouseup"))},click:function(a){c.myOptions.nonblock&&(a.stopPropagation(),l(b,a,"onclick"))},dblclick:function(a){c.myOptions.nonblock&&(a.stopPropagation(),l(b,a,"ondblclick"))}})},update:function(b,a){this.myOptions=a}}});
(function(a){"function"===typeof define&&define.amd?define("pnotify.reference",["jquery","pnotify"],a):a(jQuery,PNotify)})(function(a,f){f.prototype.options.reference={putThing:!1,labels:{text:"Spin Around"}};f.prototype.modules.reference={thingElem:null,init:function(d,f){var b=this;f.putThing&&(this.thingElem=a('<button style="float:right;" class="btn btn-default" type="button" disabled><i class="'+d.styles.athing+'" />&nbsp;'+f.labels.text+"</button>").appendTo(d.container),d.container.append('<div style="clear: right; line-height: 0;" />'),
d.elem.on({mouseenter:function(a){b.thingElem.prop("disabled",!1)},mouseleave:function(a){b.thingElem.prop("disabled",!0)}}),this.thingElem.on("click",function(){var a=0,b=setInterval(function(){a+=10;360==a&&(a=0,clearInterval(b));d.elem.css({"-moz-transform":"rotate("+a+"deg)","-webkit-transform":"rotate("+a+"deg)","-o-transform":"rotate("+a+"deg)","-ms-transform":"rotate("+a+"deg)",filter:"progid:DXImageTransform.Microsoft.BasicImage(rotation="+a/360*4+")"})},20)}))},update:function(a,f,b){f.putThing&&
this.thingElem?this.thingElem.show():!f.putThing&&this.thingElem&&this.thingElem.hide();this.thingElem&&this.thingElem.find("i").attr("class",a.styles.athing)},beforeOpen:function(a,f){},afterOpen:function(a,f){},beforeClose:function(a,f){},afterClose:function(a,f){},beforeDestroy:function(a,f){},afterDestroy:function(a,f){}};a.extend(f.styling.jqueryui,{athing:"ui-icon ui-icon-refresh"});a.extend(f.styling.bootstrap2,{athing:"icon-refresh"});a.extend(f.styling.bootstrap3,{athing:"glyphicon glyphicon-refresh"});
a.extend(f.styling.fontawesome,{athing:"fa fa-refresh"})});
